# Generated by Django 4.0.5 on 2022-07-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='제품명')),
                ('thumbnail', models.ImageField(upload_to='thumbnail', verbose_name='썸네일')),
                ('description', models.TextField(verbose_name='제품 설명')),
                ('dt_created', models.DateTimeField(auto_now_add=True, verbose_name='등록 일자')),
                ('exposure_start_date', models.DateField(verbose_name='노출 시작일')),
                ('exposure_end_date', models.DateField(verbose_name='노출 종료일')),
                ('is_active', models.BooleanField(verbose_name='활성화 여부')),
            ],
        ),
    ]
