# Generated by Django 4.0.5 on 2022-06-17 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='이름')),
                ('last_name', models.CharField(max_length=100, verbose_name='성')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='생일')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='장르를 적어주세요.', max_length=200, verbose_name='장르')),
            ],
        ),
        migrations.CreateModel(
            name='Isbn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='13자리 고유번호를 적어주세요', max_length=13, unique=True, verbose_name='책 교유번호')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='책 제목')),
                ('summary', models.TextField(help_text='책 내용을 간략하게 적어보세요.', verbose_name='책내용')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homework1.author', verbose_name='작가')),
                ('genre', models.ManyToManyField(help_text='책에 맞는 장르를 골라주세요.', to='homework1.genre', verbose_name='장르')),
                ('isbn', models.OneToOneField(help_text='고유번호 고르기', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_isbn_set', to='homework1.isbn', verbose_name='고유번호')),
            ],
        ),
    ]
